# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Tech_Unterlagen/ECS_Testat/RGB_Farbmischer/RGB_Farbmischer.cache/wt [current_project]
set_property parent.project_path C:/Tech_Unterlagen/ECS_Testat/RGB_Farbmischer/RGB_Farbmischer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo c:/Tech_Unterlagen/ECS_Testat/RGB_Farbmischer/RGB_Farbmischer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Tech_Unterlagen/ECS_Testat/RGB_Farbmischer/RGB_Farbmischer.srcs/sources_1/new/Sync.vhd
  C:/Tech_Unterlagen/ECS_Testat/RGB_Farbmischer/RGB_Farbmischer.srcs/sources_1/new/dim_log.vhd
  C:/Tech_Unterlagen/ECS_Testat/RGB_Farbmischer/RGB_Farbmischer.srcs/sources_1/new/Rstsync.vhd
  C:/Tech_Unterlagen/ECS_Testat/RGB_Farbmischer/RGB_Farbmischer.srcs/sources_1/new/pwm_dac.vhd
  C:/Tech_Unterlagen/ECS_Testat/RGB_Farbmischer/RGB_Farbmischer.srcs/sources_1/new/Ctrl.vhd
  C:/Tech_Unterlagen/ECS_Testat/RGB_Farbmischer/RGB_Farbmischer.srcs/sources_1/imports/new/pwm_led_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Tech_Unterlagen/ECS_Testat/RGB_Farbmischer/RGB_Farbmischer.xdc
set_property used_in_implementation false [get_files C:/Tech_Unterlagen/ECS_Testat/RGB_Farbmischer/RGB_Farbmischer.xdc]


synth_design -top pwm_led_top -part xc7z010clg400-1


write_checkpoint -force -noxdef pwm_led_top.dcp

catch { report_utilization -file pwm_led_top_utilization_synth.rpt -pb pwm_led_top_utilization_synth.pb }
